### ISSUE TITLE
 usePrepareBet hook doesn't update allowance value after successful transaction

### ISSUE THREAD

**Issue by Rohitbaghel** [Azuro-protocol/sdk#46]
The usePrepareBet hook from the Azuro SDK is not updating the allowance value after a successful transaction. This causes inconsistencies in the UI and potentially leads to unnecessary approval requests.
Steps to reproduce:
User initiates a bet placement that requires approval
User approves the transaction
The approval transaction is successful
4. The isApproveRequired flag doesn't update to reflect the new allowance
Expected behavior:
After a successful approval transaction, the isApproveRequired flag should update to false, reflecting the new allowance.
Current behavior:
The isApproveRequired flag remains true even after a successful approval transaction.
Possible solution:
Implement a mechanism to refetch or update the allowance value within the usePrepareBet hook after a successful approval transaction. This could involve:
Adding a callback in the onSuccess function to trigger an allowance update
Implementing a custom hook to manage allowance separately and update it after successful transactions
Modifying the usePrepareBet hook to include an allowance update mechanism

**Comment by CleanBread** [comment]
Hi, we'll check

**Comment by CleanBread** [comment]
you can upgrade version to v5.3.0
